apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: nexus.local:8081/gateway:latest  # Nexus의 도메인 및 포트로 수정
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REGISTRY_HOST
              value: "nexus.local:8081"  # Nexus 서비스의 주소로 수정

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msa-server
  template:
    metadata:
      labels:
        app: msa-server
    spec:
      containers:
        - name: msa-server
          image: nexus.local:8081/msa-server:latest  # Nexus의 도메인 및 포트로 수정
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REGISTRY_HOST
              value: "nexus.local:8081"  # Nexus 서비스의 주소로 수정

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: nexus.local:8081/client:latest  # Nexus의 도메인 및 포트로 수정
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REGISTRY_HOST
              value: "nexus.local:8081"  # Nexus 서비스의 주소로 수정
