apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: local-registry:5000/gateway:latest
          ports:
            - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msa-server
  template:
    metadata:
      labels:
        app: msa-server
    spec:
      containers:
        - name: msa-server
          image: local-registry:5000/msa-server:latest
          ports:
            - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: local-registry:5000/client:latest
          ports:
            - containerPort: 3000
